Dev tr1zel !2
bmstu-itstech/bmstu-direct pull request #5
Opened 2024-11-28 18:35 UTC by Tr1zel

Created MVP #2

2024-11-29 11:36 UTC, zhikh23 requested changes
Очень неплохо, в некоторых местах подход удивил. Но нужно исправить те замечания, что указал + подчистить код от "закомментированных строк". Пока не запускал, но выглядит работающим.

2024-11-29 11:36 UTC, zhikh23 commented on config.py
> +    chat_id3: str
Что значат `chat_idN`, знает лишь автор кода. Стараемся избавляться от цифровых индексов.

Заменить на `problem_chat_id`, `question_chat_id` и т.п. Это не избавляет от необходимости каста функцией, то есть вопрос исключительно переименования.

2024-11-29 11:36 UTC, zhikh23 commented on config.py
> +class ModChannel:
Не скажу что это один канал. Каждый чат это и есть канал. И у канала есть "сам канал" и чат, который закреплён для публикации комментариев.

2024-11-29 11:36 UTC, zhikh23 commented on config.py
> +        )
Можно обратиться к env-у один раз, записав в глобальную переменную как константу. Или вынести в условный глобальный конфиг.

2024-11-29 11:36 UTC, zhikh23 commented on core/handlers/user.py
> +channel_3 = config.channel.chat_id3 # чат для предложений
Аналогично выше, нейминг переменных.

2024-11-29 11:36 UTC, zhikh23 commented on core/handlers/user.py
> +    if message.text == 'Военная кафедра':
Вынести такие переменные в константу.

Почему это важно? Если мы поменяем текст на кнопке (а мы его поменяем), и забудем поменять в коде - пиши пропало. Попробуй сделать как у Егора, с единой местом хранения, как минимум, текста для кнопок.

2024-11-29 11:36 UTC, zhikh23 commented on core/handlers/user.py
> +        data['type'] = message.text
Такие тоже лучше выносить в константы, но уже на уровне хэндлера.
По-русски - вверху файла, после импортов сделать, например, `DATA_TYPE_KEY = "type"`.

2024-11-29 11:36 UTC, zhikh23 commented on main.py
> +from core.handlers.user import (register_user_handlers)
Почему скобки?

2024-11-29 11:36 UTC, zhikh23 commented on services/db/models.py
> +class Enum_types(enum.Enum):
Очень странная попытка наименования. Почему не PascalCase?

2024-11-29 11:36 UTC, zhikh23 commented on services/db/models.py
> +Енамы пока что нигде не используются, сделано на будущее.
)))

2024-11-29 11:36 UTC, zhikh23 commented on services/db/models.py
> +class Enum_types(enum.Enum):
Чтобы строковое перечисление работало как строковое, необходимо наследовать класс от двух:

```py
class IssueTypes(str, Enum):
    ...
```

Именно в таком порядке.

2024-11-29 11:36 UTC, zhikh23 commented on services/db/models.py
> +class Enum_types(enum.Enum):
К слову, о нейминге. Предлагаю такой вариант, чем избитое "types".

2024-11-29 11:36 UTC, zhikh23 commented on services/db/models.py
> +    is_closed = Column(Text, default=0, nullable=False)
Не уверен правильно ли мне рисует гитхаб, но проверить наличие newline-а в конце файла (то есть пустой строки). Это важно, как минимум см. стандарт PEP.

2024-11-29 13:14 UTC, Tr1zel commented on core/handlers/user.py
> +        data['type'] = message.text
Такие переменные ты имеешь ввиду data['type']? Тогда получается для каждого состояния(type, category, fio, study_group) нужна переменная?

2024-11-29 13:25 UTC, zhikh23 commented on core/handlers/user.py
> +        data['type'] = message.text
Например:

```py
DATA_TYPE_KEY = "type"
DATA_CATEGORY_KEY = "category"
...

data[DATA_TYPE_KEY] = message.text
```

2024-11-29 13:51 UTC, Tr1zel commented on config.py
> +class ModChannel:
Надо сделать в классе отдельно например ProblemsChat, ProblemsChannel?

2024-11-29 14:15 UTC, zhikh23 commented on config.py
> +class ModChannel:
Мимо. Смотри, у канала в тг не может быть три чата. Тогда есть три варианта:
- упразднить данную сущность
- переименовать во что-то, что будет обозначать не один канал, а три канала (логично же?)
- если и есть смысл рассматривать структуру, то если только пару: канал и чат комментариев. В таком случае:

```py
@dataclass
class Channel:
    post_chat_id: int     # Сам канал с постами
    comment_chat_id:  # Чат, который приклеплён к каналу как чат комментариев, куда будут сыпаться ответы на заявления
    ```

2024-12-01 12:46 UTC, zhikh23 requested changes
Ещё немножко подправить и буду мерджить)

2024-12-01 12:46 UTC, zhikh23 commented on core/states/Ticket_States.py
> +class registration(StatesGroup):
Класс с заглавной буквы.

2024-12-01 12:46 UTC, zhikh23 commented on core/text/text.py
> +class btn:
Класс с заглавной буквы.

2024-12-01 12:46 UTC, zhikh23 commented on core/text/text.py
> +    hostel = 'Общежитие' # хи-хи-хи
Убрать комментарий :)

2024-12-01 12:46 UTC, zhikh23 commented on core/text/text.py
> +    other = 'Другое'
Перевод на новую строку где?)

2024-12-01 17:02 UTC, zhikh23 requested changes
И ещё раз на доработку. Надо исправить конфигурацию бота

2024-12-01 17:02 UTC, zhikh23 commented on config.py
> +    logger.exception('Произошла ошибка при запуске')
Нет, нет и ещё раз нет. Заставлю запустить бота и пытаться угадать, где ошибка по одинокому "Произошла ошибка при запуске". Ошибка должна содержать КАК МИНИМУМ описание того, что собственно произошло. Здесь это _"не задана переменная окружения"_. Далее, в идеале, текст ошибки должен содержать такую информацию, чтобы ошибку можно было исправить или хотя бы локализовать. В нашем случае - указать, КАКУЮ переменную окружения мы забыли указать. ТО есть я должен увидеть нечто (привожу как пример) такое:

> Некорретная конфигурация бота: не задана переменная BOT_TOKEN

2024-12-01 17:39 UTC, zhikh23 approved these changes

2024-12-01 17:40 UTC, merged